### PR TITLE
Update Info.plist

### PR DESCRIPTION
**Pull request by irshadpc**

### CODE REVIEW

**Comment by i1skn** [comment]
Hi, thanks for submitting the PR. What is the reason for this change?

**Comment by irshadpc** [comment]
That is the actual message to show the users while triggering the location permission. The previous message is odd, so.

**Comment by i1skn** [comment]
Agreed, but the app does not use the user location, so this message would not be seen. I think, one of the modules references the `Core Location` framework and that's why App Store requires to provide this message. It would be good to identify this module and remove the reference to the `Core Location` framework, so we can remove the message as well.

**Comment by i1skn** [comment]
I've created an issue for this https://github.com/cyclefortytwo/ironbelly/issues/25 - let me know if it is something you would like to help with.
I would merge this one, but the main issue remains.

**Comment by irshadpc** [comment]
@i1skn will check and update.

**Pull request merged**
